#+title: dash board
#+author: Lqxc
* Write at begin
    To get work with remote server, it is time to build application that help me to sync less do more.
** project introduction
    /Key words/: Actix-Web, PostgreSql, Rescript, React
    *Actix-Web*: based on Actix, a Actor Model rust project, like other Actor Model library(Akka, elixir(PL)), single thread Actor
handle Request, an Actor won't change others state, its crash only affect itself(yes, let it crash), so Actor Model it fit for 
Concurrent System. And the newest Actix::Main based on Tokio(Rust Async library), use async to optimized app, async function
speed up the whole program, and with tokio economy, PostgreSql is support with async operation. Finally, Rust will guaranteed its
memory safety and speed with LLVM optimized and gcc support.
    *PostgreSql*: Sql, but default Concurrent way is mutli-proess not mutli-thread
    *Rescript*: Like TypeScript, it will finally compiled to JavaScript, and with config can deicide which JS Module will compiled
to(CMD or ESM), ML Model program language, like Rust, but more Functionally, pipe operator, pure function, immutable, sound type,
powerful type system, pattern matching, and raw JavaScript support, and it can generate TypeScript type and can unboxed value.
I used to use TypeScript, about 22/08/2020, but typescript its type operation not stronger enough. So I choose Rescript.
    *React*: Data Streaming Model, State Monad. More on function, more about FP. Hook, JSX changed the way we think and write.

** project structure
    As you can see, this project start from a cargo project, and it surely contains the Cargo.toml, and
I use Rescript to write my website so i need Node.js support.
    1) src: Rust source code, SqlX::Actix::Tokio::Tracing(The Whole Application build on tokio eco system)
    2) web: Rescript with React, tailwindcss,
    3) test/web: Jest, testing-library, 
    4) lib: Where rescript will compile *.res to(with bsconfig.json)
    5) target: rust will compiled here
    6) dist: esbuild will compile and zip JavaScript source code here

